name: CI - Pytest

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  python-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Always install pytest explicitly
          pip install pytest selenium webdriver-manager requests

      - name: Make results folder
        run: mkdir -p test-results

      - name: Run pytest
        run: pytest -q --maxfail=1 --disable-warnings --junitxml=test-results/pytest-report.xml

      - name: Upload pytest results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: test-results/
